ALTER TABLE tb_role DROP CONSTRAINT IF EXISTS tb_role_name_check;
ALTER TABLE tb_role ADD CONSTRAINT tb_role_name_check
    CHECK (name IN ('ROLE_USER', 'ROLE_ADMIN'));

INSERT INTO tb_role (name) VALUES ('ROLE_USER') ON CONFLICT DO NOTHING;
INSERT INTO tb_role (name) VALUES ('ROLE_ADMIN') ON CONFLICT DO NOTHING;